export const colorPalettes = {
  // cancel: "red",
  // cardBackground: "#fff",
  // title: "#fff",
  // titleBorder: "#fff",
  shadowColor: "#171717",
  // startBackground: ['#ffafcc', '#bde0fe', '#a2d2ff'],
  // confirmBackground: ['#fb8500', '#023047', '#219ebc'],
  // finishBackground: ['#dad7cd', '#588157', '#3a5a40'],
  headerBackground: "#6096B4",
  headerText: "#FCFFE7",
  screenBackground: "#93BFCF",
  itemText: "#4D455D",
  itemBackground: "#BAD7E9",
  caloryBackground: "#FCFFE7",
  text: "#13005A",
  button: "#BDCDD6",
  buttonText: "#4D455D",
  buttonPressed: "#97A4AB",
  editCardBackground: "#FCFFE7",
  cancelButtonBackground: "#BDCDD6",
  confirmButtonBackground: "#BDCDD6",
}